### PR TITLE
Fix packaging

### PR DESCRIPTION
**Pull request by jrha**
Rebase @piojo's packaging work and configure `setup.py` correctly.

### CODE REVIEW

**Comment by jrha** [comment]
@urbonegi this got forgotten, could you have a look at it?

**Comment by urbonegi** [comment]
@jrha PR merged. Could we build and upload the package to the repo or it is there already?

**Comment by jrha** [comment]
There is an older version there already, I'll add building a new one to my todo list.

**Comment by urbonegi** [comment]
@jrha Ok! Also the latest code was synced to the project from MS, so we should definitely package the latest release of the aquilon-protocols as there are dependencies (new protocols) in Aquilon broker for the new version.

**Pull request closed without merging**
