### PR TITLE
Fix setup.py

### PR DESCRIPTION
**Pull request by jrha**
Was broken by moving the source files in 8d80c69b4ebaddfcaa10467d3a9b7197bcb362e0.

### CODE REVIEW

**Review by jouvin — APPROVED** [review]

**Comment by jouvin** [comment]
@jrha I approved your changes (thanks for them! they work well) but I don't remember if this repository has a specific merge policy as for the main Aquilon repo. Else, I'm happy to merge it.

**Comment by jrha** [comment]
Exactly the same policy, @urbonegi has to pull in via Gerrit at MS

**Comment by jouvin** [comment]
Ok, so nothing more to do for this PR?

**Comment by jrha** [comment]
Nope!

**Comment by urbonegi** [comment]
Hey, will do - noted.

**Comment by jrha** [comment]
Cool! I'm going to assume everything is above board with the merge as @ned21 was the one who added @Shaeli to the aquilon team.

**Comment by xaf** [comment]
@Shaeli is currently in internship with us :)

**Comment by jrha** [comment]
Cool! Welcome!

**Pull request merged**
